### ISSUE TITLE
mpich-4.1a1 memory leaks on Ubuntu 20 with default gcc 9.4.0

### ISSUE THREAD

**Issue by dqwu** [pmodels/mpich#6342]
This issue is reproducible on most ANL CELS GCE nodes with Ubuntu 20 (e.g. compute-10.cels.anl.gov)
```
gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
```

Also reproducible with mpich-4.1b1, but not reproducible with mpich-4.0.3.

Steps to reproduce
```
wget https://www.mpich.org/static/downloads/4.1a1/mpich-4.1a1.tar.gz
tar zxf mpich-4.1a1.tar.gz
cd mpich-4.1a1

./configure --prefix=/path/to/mpich/installation --with-device=ch3 --disable-fortran --with-hwloc=embedded
make -j8
make install

export PATH=/path/to/mpich/installation/bin:$PATH

cat <<EOF >> test_mpi.c
#include <mpi.h>
int main(int argc, char *argv[])
{
  MPI_Init(&argc, &argv);
  MPI_Finalize();

  return 0;
}
EOF

mpicc -fsanitize=leak test_mpi.c
mpiexec -n 2 ./a.out
```

Leak Sanitizer report
```
=================================================================
==4023528==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7f2bd8d8dd46 in __interceptor_realloc ../../../../src/libsanitizer/lsan/lsan_interceptors.cpp:82
    #1 0x7f2bd8b4e1c3 in hwloc__add_info (/home/wuda/3rdparty/mpich_4.1a1_ch3/lib/libmpi.so.0+0x2f51c3)
    #2 0x7f2bd8b7c83b in hwloc__xml_import_cpukind (/home/wuda/3rdparty/mpich_4.1a1_ch3/lib/libmpi.so.0+0x32383b)
    #3 0x7f2bd8b7d549 in hwloc_look_xml (/home/wuda/3rdparty/mpich_4.1a1_ch3/lib/libmpi.so.0+0x324549)
    #4 0x7f2bd8b5500b in hwloc_discover (/home/wuda/3rdparty/mpich_4.1a1_ch3/lib/libmpi.so.0+0x2fc00b)
    #5 0x7f2bd8b5675a in hwloc_topology_load (/home/wuda/3rdparty/mpich_4.1a1_ch3/lib/libmpi.so.0+0x2fd75a)
    #6 0x7f2bd8abe1ee in MPII_hwtopo_init (/home/wuda/3rdparty/mpich_4.1a1_ch3/lib/libmpi.so.0+0x2651ee)

Indirect leak of 21 byte(s) in 2 object(s) allocated from:
    #0 0x7f2bd8d8d9c1 in __interceptor_malloc ../../../../src/libsanitizer/lsan/lsan_interceptors.cpp:54
    #1 0x7f2bd870638e in __GI___strdup /build/glibc-SzIz7B/glibc-2.31/string/strdup.c:42

SUMMARY: LeakSanitizer: 149 byte(s) leaked in 3 allocation(s).
```
@raffenet A similar issue (#5863) has been reported and fixed before. Your suggested workaround "--with-hwloc=embedded" no longer works. Looks like a regression since 4.0.3 cannot reproduce this issue.

**Comment by raffenet** [comment]
OK, I will take a look.

**Comment by raffenet** [comment]
Need to update our submodule to include https://github.com/open-mpi/hwloc/pull/547. PR incoming.
