### ISSUE TITLE
Cannot configure mpich in separate build directory

### ISSUE THREAD

**Issue by eschnett** [pmodels/mpich#6848]
This fails with the current HEAD of mpich:

```sh
mkdir build
cd build
../configure
```

The error message (which does not abort configure!) is
```
  --> [src/binding/fortran/use_mpi_f08/mpi_f08_types.f90]
Traceback (most recent call last):
  File "/Users/eschnett/src/mpich/build-gcc/../maint/gen_binding_f08.py", line 171, in <module>
    main()
  File "/Users/eschnett/src/mpich/build-gcc/../maint/gen_binding_f08.py", line 164, in main
    load_mpi_h_in("src/include/mpi.h.in")
  File "/Users/eschnett/src/mpich/maint/local_python/binding_f08.py", line 1680, in load_mpi_h_in
    with open(f, "r") as In:
FileNotFoundError: [Errno 2] No such file or directory: 'src/include/mpi.h.in'
```

I think there is a path prefix missing in this Python script.

Errors in this script should also abort `configure`.

`gen_binding_f77.py` and `gen_binding_f90.py` are also affected.

**Comment by eschnett** [comment]
Thanks for the recent changes, they helped a lot. I now see
```
make[2]: Entering directory '/Users/eschnett/src/mpich/build-gcc'
  CC       src/mpi/datatype/create_f90.lo
../src/mpi/datatype/create_f90.c:7:10: fatal error: mpif90model.h: No such file or directory
    7 | #include "mpif90model.h"
      |          ^~~~~~~~~~~~~~~
```
