### ISSUE TITLE
hydra: segfault when machine has thousands of IP addresses.

### ISSUE THREAD

**Issue by xiaoyao9933** [pmodels/mpich#7020]
When in a kubelet IPVS environment, with thousands of ip addresses on interface kube-ipvs0, mpich will got segment fault when run 'mpirun -n 2 hostname'. There seems to have a memory overflow when iterating local ip address and proxy_list structure is corrupted.

using latest mpich 4.2.1 version.

```
$ ./mpiexec.hydra -n 2 hostname
Segmentation fault (core dumped)
$ gdb ./mpiexec.hydra                  
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./mpiexec.hydra...done.
(gdb) r -n 2 hostname
Starting program: /home/user/mpich/mpich-4.2.1/install/bin/mpiexec.hydra -n 2 hostname
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
warning: the debug information found in "/usr/lib/debug//lib/x86_64-linux-gnu/librt-2.27.so" does not match "/lib/x86_64-linux-gnu/librt.so.1" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//lib/x86_64-linux-gnu/librt-2.27.so" does not match "/lib/x86_64-linux-gnu/librt.so.1" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//lib/x86_64-linux-gnu/libnss_files-2.27.so" does not match "/lib/x86_64-linux-gnu/libnss_files.so.2" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//lib/x86_64-linux-gnu/libnss_files-2.27.so" does not match "/lib/x86_64-linux-gnu/libnss_files.so.2" (CRC mismatch).


Program received signal SIGSEGV, Segmentation fault.
__strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:31
31      ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  __strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:31
#1  0x0000555555596fc2 in append_lhost ()
#2  0x000055555559715a in init_lhost_list ()
#3  0x00005555555971d8 in MPL_host_is_local ()
#4  0x000055555555b898 in main (argc=<optimized out>, argv=<optimized out>) at mpiexec/mpiexec.c:229
(gdb) r
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /home/user/mpich/mpich-4.2.1/install/bin/mpiexec.hydra -n 2 hostname
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
warning: the debug information found in "/usr/lib/debug//lib/x86_64-linux-gnu/librt-2.27.so" does not match "/lib/x86_64-linux-gnu/librt.so.1" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//lib/x86_64-linux-gnu/librt-2.27.so" does not match "/lib/x86_64-linux-gnu/librt.so.1" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//lib/x86_64-linux-gnu/libnss_files-2.27.so" does not match "/lib/x86_64-linux-gnu/libnss_files.so.2" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//lib/x86_64-linux-gnu/libnss_files-2.27.so" does not match "/lib/x86_64-linux-gnu/libnss_files.so.2" (CRC mismatch).


Program received signal SIGSEGV, Segmentation fault.
__strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:31
31      ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  __strcmp_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:31
#1  0x0000555555596fc2 in append_lhost ()
#2  0x000055555559715a in init_lhost_list ()
#3  0x00005555555971d8 in MPL_host_is_local ()
#4  0x000055555555b898 in main (argc=<optimized out>, argv=<optimized out>) at mpiexec/mpiexec.c:229
(gdb) 
```

my ip addresses in ipvs of kubelet environment:

```
# other interface.
32: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default 
    link/ether fe:06:c8:e4:2e:a1 brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.10/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.195.72/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.115.165/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.9.231/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.255.103/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.100.8/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.117.71/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.105.101/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.23.19/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.77.200/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.124.3/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.109.138/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.100.17/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.62.254/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.233.101/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.84.133/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.100.111/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.14.2/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.157.23/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.95.6/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.14.91/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.135.198/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.215.91/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.79.137/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.178.87/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.159.178/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.21.193/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.23.112/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.10.147/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.58.218/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.114.123/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.86.246/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.145.154/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.247.31/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.194.19/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.152.88/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.249.213/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.244.28/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.232.135/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.30.112/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.77.212/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.181.84/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.212.142/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.139.221/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.244.230/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 172.16.77.96/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever


#more with thousands of ip address.
```

**Comment by hzhou** [comment]
Thanks for reporting the issue. PR #7022 should fix the segfault.
